version: "3.7"

services:
  # Development container. 
  # Runs in debug mode and live-reloading on every source file update.
  auth-dev:
    hostname: auth-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      ./.env
    volumes:
      - ./:/app
    ports:
      - "8888:8888"

  auth:
    hostname: auth
    restart: unless-stopped
    build:
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      ./.env
    volumes:
      - ./.env:/app/.env
    ports:
      - "8888:8888"
    # command: tail -f /dev/null